%% get_file_details

function [file_struct] = get_file_details(filelist)

filenames = string({filelist.name});
expr = ['(?<date>^\d\d\d\d\d\d\d\d)[_]'...
    '(?<time>\d\d\d\d\d\d)[@]'...
    '(?<driver>[\w()]*)[@]'...
    '(?<effector>[\w()]*)[@]'...
    '(?<tracker>[t]\d*)[@]'...
    '[#](?<prot1>\w*)'...
    '[#](?<prot2>\w*)'...
    '[#](?<prot3>\w*)'...
    '[#](?<prot4>\w*)[@]'...
    '\d*[@]'...
    '[.](?<filetype>\w*)[.]'];


file_struct = regexp(filenames,expr,'names','forcecelloutput');
file_struct = vertcat(file_struct{:});

fullgeno = strcat([file_struct.driver],'@',[file_struct.effector]);
for ii = 1:length(file_struct)
    file_struct(ii).full_genotype = fullgeno(ii);
end