choreography_config:
  features: ['speed','area','x','y','curve','spine']
  pval: 0.0528
  choreLoc: ./packages/choreography/Chore.jar
  M: 0.18
  t: 5
  s: 0.1
  rig: t93
  runQuiet: true

directories: 
  master: .
  mwt: ./data/mwt_data
  choreography_output: ./data/chore_output
  choreography_input: ./data/chore_input
  code: ./code
  figures: ./figures

filetypes:
  blobs: .blob*
  chore_txt: compiledChore.txt
  chore_dat: .dat
  salam: animal_stats*.txt
  jaaba: [trx.mat, scores*short.mat]
  jb: trx.mat
